backend:
  name: git-gateway

media_folder: static/assets
public_folder: assets

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "static/content/services/services.md"
        label: "Services Page"
        name: "services"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "services-page-content" }
          - { label: "title description", name: "titleDescription", widget: "text", required: false }
          - { label: "immigration description", name: "immigrationDescription", widget: "string" }
          - { label: "visa description", name: "visaDescription", widget: "string" }
          - { label: "lmia description", name: "lmiaDescription", widget: "string" }
          - { label: "humanities description", name: "humanitiesDescription", widget: "string" }
          - { label: "citizenship description", name: "citizenshipDescription", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "static/content/citizenship/citizenship.md"
        label: "Citizenship Page"
        name: "citizenship"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "citizenship-page-content" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "static/content/humanities/humanities.md"
        label: "Humanities Page"
        name: "humanities"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "humanities-page-content" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "static/content/lmia/lmia.md"
        label: "LMIA Page"
        name: "lmia"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "lmia-page-content" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "static/content/visa/visa.md"
        label: "Visa Page"
        name: "visa"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "visa-page-content" }
          - { label: "title description", name: "titleDescription", widget: "text", required: false }
          - { label: "guest visa description", name: "guestVisaDescription", widget: "string" }
          - { label: "student visa description", name: "studentVisaDescription", widget: "string" }
          - { label: "work visa description", name: "workVisaDescription", widget: "string" }
          - { label: "super visa description", name: "superVisaDescription", widget: "string" }
          - { label: "restoration visa description", name: "restorationStatusDescription", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "static/content/guestVisa/guestVisa.md"
        name: "guestVisa"
        label: "Guest Visa Page"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "guest-visa-page-content" }
          - { label: "title description", name: "titleDescription", widget: "text", required: false }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "static/content/workVisa/workVisa.md"
        name: "workVisa"
        label: "Work Visa Page"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "work-visa-page-content" }
          - { label: "title description", name: "titleDescription", widget: "text", required: false }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "static/content/studentVisa/studentVisa.md"
        name: "studentVisa"
        label: "Student Visa Page"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "student-visa-page-content" }
          - { label: "title description", name: "titleDescription", widget: "text", required: false }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "static/content/restorationStatus/restorationStatus.md"
        name: "restorationStatus"
        label: "Restoration Status Page"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "restoration-status-page-content" }
          - { label: "title description", name: "titleDescription", widget: "text", required: false }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "static/content/superVisa/superVisa.md"
        name: "superVisa"
        label: "Super Visa Page"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "super-visa-page-content" }
          - { label: "title description", name: "titleDescription", widget: "text", required: false }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "static/content/immigration/immigration.md"
        name: "immigration"
        label: "Immigration Page"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "immigration-page-content" }
          - { label: "Title", name: "title", widget: "text", required: true }
          - { label: "title description", name: "titleDescription", widget: "text", required: false }
          - { label: "After Content Topic", name: "afterContentTopic", widget: "text", required: false }
          - { label: "ExpressEntryDescription", name: "expressEntryDescription", widget: "string" }
          - { label: "ProvincialProgramsDescription", name: "provincialProgramsDescription", widget: "string" }
          - { label: "BusinessImmigrationDescription", name: "businessImmigrationDescription", widget: "string" }
          - { label: "Family Sponsorship Description", name: "familySponsorshipDescription", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "static/content/expressEntry/expressEntry.md"
        name: "expressEntry"
        label: "Express Entry Page"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "express-entry-page-content" }
          - { label: "Title", name: "title", widget: "text", required: true }
          - { label: "title description", name: "titleDescription", widget: "text", required: false }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "static/content/provincialPrograms/provincialPrograms.md"
        name: "provincialPrograms"
        label: "Provincial Programs Page"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "provincial-programs-page-content" }
          - { label: "Title", name: "title", widget: "text", required: true }
          - { label: "title description", name: "titleDescription", widget: "text", required: false }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "static/content/businessImmigration/businessImmigration.md"
        name: "businessImmigration"
        label: "Business Immigration Page"
        fields:
           - { label: "Template Key", name: "templateKey", widget: "hidden", default: "business-immigration-page-content" }
           - { label: "Title", name: "title", widget: "text", required: true }
           - { label: "title description", name: "titleDescription", widget: "text", required: false }
           - { label: "Body", name: "body", widget: "markdown" }
      - file: "static/content/familySponsorship/familySponsorship.md"
        name: "familySponsorship"
        label: "Family Sponsorship Page"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "family-sponsorship-page-content" }
          - { label: "Title", name: "title", widget: "text", required: true }
          - { label: "title description", name: "titleDescription", widget: "text", required: false }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "questions"
    label: "Questions"
    folder: "static/content/questions"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
  - name: "reviews"
    label: "Reviews"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    folder: "static/content/reviews"
    identifier_field: name
    editor:
      preview: false
    fields:
      - { label: "Avatar", name: "avatar", widget: "image" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
  - name: "news"
    label: "News"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    folder: "static/content/news"
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "news-item-content" }
      - { label:  "Title", name: "title", widget: "string"}
      - { label: "Detail", name: "detail", widget: "string" }
      - { label: "Cover image", name: "coverImage", widget: "image" }
      - { label: "Publish date", name: "publishDate", widget: "datetime", default: "", dateFormat: "DD/MM/YYYY", timeFormat: false }
      - { label: "Body", name: "body", widget: "markdown" }

